### ISSUE TITLE
Incremental Search - what, where?

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [microsoft/XmlNotepad#162]
I tried the "Incremental search" - and felt a little helpless. I see the "search icon", but I don't see what I typed, how to reset what I typed and if it searches also inside the strings (It seems that it search only at the beginning of the strings - typing "note" will not find "xmlnotepad")

**Comment by lovettchris** [comment]
Yeah, I agree, you can reset by typing Ctrl+I again and yes, it only searches from the beginning of things otherwise it might jump around like mad finding matching substrings.  I use it mostly only in the tree view, but I think it would be more useful there if it auto-expanded things to show you the matching element you are looking for...

**Comment by Pierre-de-la-Verre** [comment]
After working with it I think I found the basic functionality of this feature.
