### ISSUE TITLE
[GUI] The tree-view wastes WAY TOO MUCH SPACE!

### ISSUE THREAD

**Issue by HackerDaGreat57** [microsoft/XmlNotepad#204]
First, I would like to thank you for making such an amazing application and even making it open source. I am using it to plan my game's save file format.

However, the tree-view wastes way too much space! What I mean by that is, it looks like this
![image](https://user-images.githubusercontent.com/70416002/167969911-fb0bf66a-232d-483b-8f3d-3488718e33a4.png)
when it would waste a lot less space if it were to look like this (sorry about the text being different - this is from a different Win32 app)
![image](https://user-images.githubusercontent.com/70416002/167969993-d19bf82d-3ab6-4397-93ff-b3cdb0c7df78.png)

In case you haven't already figured it out, I'm talking about **reducing the horizontal length of the lines** or at least making it manually configurable somewhere in the settings dialog.

Thanks in advance.

**Comment by lovettchris** [comment]
Hi thanks for playing with XML Notepad.  I think the vertical space is limited by the Text and therefore the font size, and not the "dotted line connectors", for example, this blue highlight shows the text is taking up the entire height of that line:
![image](https://user-images.githubusercontent.com/18707114/167973974-9024c1e9-80b8-4c06-a40d-fccd7fa6492b.png)

therefore you can reduce the vertical space taken by reducing the font size in the View/Options dialog.  Text labels do look like they take up more space than they need to in general, and this is usually because there are always some weird letters in a given font that take a lot of space.  For example, I'm using Consolas font and you can see below the full space is used when I use some letters with accents and long tails like this and in general having vertical space change depending on the content tends to be frowned upon in UI design because it looks messy.  Text rendering likes to have a fixed line height per font.

![image](https://user-images.githubusercontent.com/18707114/167974004-f56018ee-f734-4e7e-bd18-fa11320121bf.png)

**Comment by HackerDaGreat57** [comment]
I... I am very sorry. 🤦‍♂️I meant to say "horizontal" dotted lines

**Comment by lovettchris** [comment]
Ah, so you want smaller horizontal indent?  Yes, this I can add easily, I'll add an option for it so you can configure it to your liking.

**Comment by HackerDaGreat57** [comment]
Thanks a bunch! 😁

**Comment by lovettchris** [comment]
Feature added in https://github.com/microsoft/XmlNotepad/commit/103e6a40fecc79df35352e1d71d8d59e597d1d31

**Comment by lovettchris** [comment]
The new feature is included in version 2.8.0.60.

**Comment by HackerDaGreat57** [comment]
Thanks.
