### ISSUE TITLE
Missing updates.xml and link to it

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [microsoft/XmlNotepad#222]
I'm not sure, but there was an update.xml in the installation path, correct? I can't find it?
Edit: Found it. It is in the ZIP, not inside the installed folder.

And
file:///C:/Program%20Files%20(x86)/LovettSoftware/XmlNotepad/Help/index.html
links to
http://lovettsoftware.com/downloads/xmlnotepad/Updates.xml
which is 404 ..

**Comment by lovettchris** [comment]
There's a link to it on this help page: https://microsoft.github.io/XmlNotepad/#help/updates/
which takes you here: 
https://github.com/microsoft/XmlNotepad/blob/master/src/Updates/Updates.xml

It also lives here if you want to view the XSLT rendering of it:
https://lovettsoftwarestorage.blob.core.windows.net/downloads/XmlNotepad/Updates.xml

**Comment by lovettchris** [comment]
And thanks for the broken link report.  It is fixed in this change: https://github.com/microsoft/XmlNotepad/commit/dc3a0987717cc4d874063bd1c3897bf0b4f1fe0e

**Comment by NotepadPlusUser** [comment]
Is this is the same problem?  I went to https://github.com/microsoft/XmlNotepad/releases/
then selected Xml Notepad 2.8.0.62, Assets, Second asset of 4,
That downloaded XmlNotepadSetup.zip.  But it was V2.8.0.61.  Even though the Updates.xml file in the unzipped folder gave details for V2.8.0.62 

I had to go to https://microsoft.github.io/XmlNotepad/#install/ and download the standalone installer there to get the new V2.8.0.62.  

But that page is a nuisance, because it does not give the version and release date, so it unfortunately can't be used as reference to keep an eye on updates.

**Comment by lovettchris** [comment]
Hmmm, ok, thanks for the info about the standalone installer, I will check my build setup and make sure it contains the right version in the future.

The ClickOnce installer is the most convenient because it will "auto-update".  Every day it will check if a new version is available and if one is available it will download it, and next time you launch XML notepad it will auto-install that new version and use it.

**Comment by NotepadPlusUser** [comment]
Thanks, Chris.  I see that the MSI file is now V2.8.0.62, as it should be.

Thanks also for the tip about ClickOnce.  I won't use it, however, because being Old School, I like to see the version number and release date of each piece of software, and then download and update it.  

If you could post the version and date just below the ClickOnce Button, next to the Standalone Installer button, then it would be as glorious as the proclamation of the new King Charles III.

**Comment by lovettchris** [comment]
Fixed in https://github.com/microsoft/XmlNotepad/releases/tag/2.8.0.63
