### ISSUE TITLE
Executable location

### ISSUE THREAD

**Issue by athertonk** [Microsoft/XmlNotepad#32]
Where is the app located? I'm trying to associate .xml files to this app and I can't find it anywhere in the store or on my hard drive. I have a shortcut in my Start Menu, but can't figure out where it's launching from.
Thanks.

**Comment by athertonk** [comment]
Sorry, nevermind. Just needed to go to the Start Menu folder and select it.

**Comment by lovettchris** [comment]
Yeah, clickonce apps run from a sandbox located like this:
```
C:\Users\Chris\AppData\Local\Apps\2.0\60MPBT3D.ELV\H2QGHQ42.AJQ\xmln..tion_ab3ea86545595e2b_0002.0007_3f6d9d58fdf3015b\XmlNotepad.exe
```
You can find this using Task Manager right click on running XML notepad process and select Properties.  What we should do is add a menu item to XML notepad that says "Make Default App" or something that let's you pick the file extensions you want, and then XML notepad can do the magic for you... (since windows makes this so difficult, and gets it wrong).
