### ISSUE TITLE
Upgrading leaves old files

### ISSUE THREAD

**Issue by DustinLuck** [microsoft/XmlNotepad#328]
Observed behavior:
Upgrading from v2.8.0.64 to v2.9.0.5 leaves old files behind.

Expected behavior:
Files that are no longer needed should be removed.

Steps to reproduce:

1. Run the v2.9.0.5 installer and choose the location of the installed v2.8.0.64 application.
2. Copy the application folder to another location.
3. Unistall v2.9.0.5.
4. Run the v2.9.0.5 installer.
5. Compare the files from the backup location in step 2 to the new installation in step 4.

These are the files from the previous version that were not cleaned up:

- \help\clipboard.htm
- \help\customeditors.htm
- \help\dragdrop.htm
- \help\find.htm
- \help\intellisense.htm
- \help\keyboard.htm
- \help\menus.htm
- \help\options.htm
- \help\overview.htm
- \help\schemas.htm
- \help\ui.htm
- \help\updates.htm
- \help\validation.htm
- \runtimes\win-x64\native\WebView2Loader.x64.dll

System Information:
Windows 10 Enterprise v21H2
v2.8.0.64 starting point was a portable installation

**Comment by lovettchris** [comment]
I'm not sure this is a scenario that my setup technology supports, see: https://wixtoolset.org/docs/wix3/

You did not uninstall v2.8.0.64 right? So windows thinks you still have v2.8.0.64 installed, and perhaps these help files belong to that install so that's why they were not removed?

But in general I don't want to support this kind of complexity during setup, the .msi standalone installer is provided as a convenience only for folks that cannot use the ClickOnce or winget installers and .msi is not a technology I want to become an expert in since everyone is moving to .msix, ClickOnce and winget and these newer install technologies solve this problem by always creating a new folder for the new version.
