### ISSUE TITLE
Spaces in XmlNotepad solution path breaks Unit tests.

### ISSUE THREAD

**Issue by shadolight** [microsoft/XmlNotepad#35]
Unit tests cannot be executed if the XmlNotepad Solution is located in a path with spaces in the path. For example c:\users\john smith\will\not\work\XmlNotepad.

In addition all unit tests that uses this pattern...
            p = pivalue.Bounds.Center();
            var hit = ntv.HitTest(p.X, p.Y);
            string hitname = hit.Name;
..fails on my computer.

**Comment by lovettchris** [comment]
fixed bugs in handling of folder paths containing spaces.  I also made TestIntellisense a bit more robust. As you can see the unit tests are using System.Windows.Automation and the coordinates returned from this API are used sometimes to move and click the mouse.  This is done using the Win32 SendInput API.  If this is not working for you then I wonder if there is some sort of DPI mismatch between these two API's.  Specifically if you use this Setting on Windows 10, then the tests might fail because of that.  But I tried various settings here and the tests still pass.  So I'd be curious what you find with the "inspect.exe" tool included in the Windows SDK. 

![image](https://user-images.githubusercontent.com/18707114/58767620-01bd5880-8543-11e9-92ac-6368b24c631c.png)
