### ISSUE TITLE
Question: missing line-break when using XSLT identity transformation

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [microsoft/XmlNotepad#379]
It seems that I set a wrong configuration ...

I have a simple "XSLT identity transformation", and using it with xsl.exe it works fine and keeps all line-feeds.

When I use it with XmlNotepad, it transform the file too, but removes all line-feeds. I have to reformat it with xmlint.exe.
I changed all my settings for XmNotepad to "Default" - no solution either.
How can I keep the line-feeds?

**Comment by lovettchris** [comment]
Hmm, this one is a bit tricky, if I turn on "Preserve Whitespace" in the XML Document then you will see this:

![image](https://github.com/microsoft/XmlNotepad/assets/18707114/e6581dc7-6cdc-45a0-8768-0616c909ca9f)

I assume you do not want to see whitespace like this, or do you?  In order to have full control over whitespace in the document (and see it in the XSLT transform) you kind of need this, but it's pretty tedious...?

The alternative (1) is I hide all these nodes in the XML notepad UI, but I load the whitespace nodes into the document so XSLT transforms can see the whitespace.

Alternative (2) which saves memory, would be to not load any whitespace into the document, but before I run the XSLT transform I save the document with pretty printing turned on (which xml notepad save is doing already) and then I feed that saved document with whitespace to the XSLT transform.  The downside of this is that for very large documents this could add a lot of time before you see the XSLT output due to having to save and reload that doc into the transform.

What is your preference?

**Comment by lovettchris** [comment]
I ended up adding a new Option under formatting called "Preserve Whitepsace" so you can play with that and see what you think, after turning it on you will need to reload your XML doc and you will see the above `#whitespace` nodes.

**Comment by Pierre-de-la-Verre** [comment]
Hi Chris
I'm not sure we are talking about the same topic.

I have this XML in UTF-8:
```
<?xml version="1.0" encoding="utf-8"?>
<DSS_2015_LV95.Siedlungsentwaesserung.Einzugsgebiet TID="12684">
  <OBJ_ID>12684</OBJ_ID>
  <Metaattribute>
    <SIA405_Base_LV95.Metaattribute>
      <Letzte_Aenderung>20211124</Letzte_Aenderung>
    </SIA405_Base_LV95.Metaattribute>
  </Metaattribute>

</DSS_2015_LV95.Siedlungsentwaesserung.Einzugsgebiet>

```
This XSLT (ident copy):
```
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
  <xsl:template match="@*|node()">
    <xsl:copy >
      <xsl:apply-templates select="@*|node()"/>
    </xsl:copy>
  </xsl:template>
</xsl:stylesheet>
```

With your xsl.exe 1.0 from your XMLTools 2023-01-27 I use this command:
`xsl -s ident_kopie.xslt mini.xml`

and get this result:
```
<?xml version="1.0" encoding="utf-8"?><DSS_2015_LV95.Siedlungsentwaesserung.Einzugsgebiet TID="12684">
  <OBJ_ID>12684</OBJ_ID>
  <Metaattribute>
    <SIA405_Base_LV95.Metaattribute>
      <Letzte_Aenderung>20211124</Letzte_Aenderung>
    </SIA405_Base_LV95.Metaattribute>
  </Metaattribute>

</DSS_2015_LV95.Siedlungsentwaesserung.Einzugsgebiet>
```

Using the same in XMLNotepad I get this result - with missing line-breaks:
```
<?xml version="1.0" encoding="utf-8"?><DSS_2015_LV95.Siedlungsentwaesserung.Einzugsgebiet TID="12684"><OBJ_ID>12684</OBJ_ID><Metaattribute><SIA405_Base_LV95.Metaattribute><Letzte_Aenderung>20211124</Letzte_Aenderung></SIA405_Base_LV95.Metaattribute></Metaattribute></DSS_2015_LV95.Siedlungsentwaesserung.Einzugsgebiet>

```

**Comment by lovettchris** [comment]
Please re-read my answers, this is about "preserving whitespace" in the XML Document, which XML notepad does not do by default.  Try my new Preserve Whitespace setting and you will get the XSL output you are looking for.

**Comment by lovettchris** [comment]
New Preserve Whitespace formatting option is available in https://github.com/microsoft/XmlNotepad/releases/tag/2.9.0.9

**Comment by Pierre-de-la-Verre** [comment]
Thanks, works as expected.
