### ISSUE TITLE
Handling of "insert empty values"

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [microsoft/XmlNotepad#420]
The handling of inserting empty values into the tree seem to be inconsistent.

Got to the tree view and ..

a) press "insert" (or right mouse: insert) - escape - escape: An empty value is inserted
b) press "insert" (or right mouse: insert)  - click to another element - the warning appears, I answer with "No" - it creates the empty value anyway and jumps to the newly selected element

**Comment by clovett** [comment]
It's because Escape is normally a cancel operation, so it is equivalent to typing:
"insert", "enter" wait for the popup the warning to appear, then press "yes".

Why would you want to do this? Well sometimes you need to copy the name you are about to enter from someplace else, you go there and copy the name then go back to the empty element, press ENTER to edit it again, and paste the name you wanted there.

**Comment by clovett** [comment]
So the dialog says "You must provide a non-empty name, are you sure you want to leave this name empty?" and if you answer:
- yes - then it commits the edit with an empty name
- no - then it does not commit the edit, and leaves the node in edit mode and with the keyboard focus so you can type a name.

**Comment by Pierre-de-la-Verre** [comment]
Oh, now I understand. 
I took "no" for an absolute "no" - do nothing, accept nothing.
