### ISSUE TITLE
Very large XML's hang for a long time on edit

### ISSUE THREAD

**Issue by sbalderrama** [microsoft/XmlNotepad#51]
If you have a very large XML, and edit something towards the end of the XML, it will hang up for a substantial amount of time.  Even on not so large XML's the time delay after editing a node value is noticeable.

The source of the delay is the CheckChange call in XmlTreeView.OnModelChanged, which appears to be doing an exhaustive search of the XML document on every edit.

**Comment by GlacierEclipse** [comment]
@sbalderrama 
Hey, I've encountered the same issue as I work with large XMLs as-well, I think it has to do with this line:
https://github.com/microsoft/XmlNotepad/blob/549d447910d9dd64e230f906320b4f8821d642c2/src/XmlNotepad/XmlTreeView.cs#L528
The first condition runs FindNode(node) (super heavy) even when we are not saving, moving that condition to the end I went from duplicating large nodes taking ~11 sec to ~100ms.

**Comment by clovett** [comment]
Oh, hey nice find, this FindNode call is indeed bogus, and the FindNode implementation was also very bad, expanding everything rather than just the immediate parent chain to the desired node, so I've fixed both of these issues in 2.8.0.18.  This will also greatly improve performance of "Find" on large documents.
