### ISSUE TITLE
Start Menu Icon Scaling

### ISSUE THREAD

**Issue by slestak** [microsoft/XmlNotepad#61]
Using 2.8.0.14 on Win 10 2004 (19041.450).

When adding the app to the start menu, the icon scales very small.  See attached screenshot.
![Annotation 2020-08-31 093703](https://user-images.githubusercontent.com/79189/91726024-8e532e00-eb6d-11ea-8dff-983e69b49658.png)

**Comment by lovettchris** [comment]
Yeah, good point, the icon artwork is very old where the largest image in the icon is 48x48 pixels, which of course it tiny in today's standards.  How's this version?

![image](https://user-images.githubusercontent.com/18707114/91750489-07578300-eb78-11ea-9778-7a8cd699a5b3.png)

:-)

**Comment by slestak** [comment]
Works for my tired eyes.  If it is ok, going to rapid fire issues.  Got another one to enter.

**Comment by Jaiganeshkumaran** [comment]
Is this the MSIX version or the regular version?

**Comment by lovettchris** [comment]
Both, the fix is in version 2.8.0.16.  This is the new start icon:
![image](https://user-images.githubusercontent.com/18707114/92879400-df5eef80-f3c1-11ea-84fc-8fe0ed31280d.png)

the file icon goes even bigger:
![image](https://user-images.githubusercontent.com/18707114/92879564-fd2c5480-f3c1-11ea-9eb6-1dc93fe5e354.png)

not sure why the start menu doesn't allow bigger icons, but at least it is not tiny any more.
