### ISSUE TITLE
Ability to disable Google Analytics by default

### ISSUE THREAD

**Issue by rcadmin19** [microsoft/XmlNotepad#70]
Is there any method to disable Google Analytics by default for example with MSI parameter? I did not find any other method either to disable this feature by default. Not so nice function in enterprise use.

**Comment by lovettchris** [comment]
There is no .msi parameter.  On first launch on a machine that has not had XML notepad installed before you will see this dialog:
![image](https://user-images.githubusercontent.com/18707114/108260104-c26bdc80-7116-11eb-9f28-415be082f9d4.png)
and if user clicks No then the choice will be written to the XML Notepad settings file and it will not be prompted again.

So you could create this file before running the installer:

```
%LOCALAPPDATA%\Microsoft\Xml Notepad\XmlNotepad.settings
```
containing the following:
```xml
<Settings>
  <AnalyticsClientId>12bd06be-3916-4698-a41b-b3ad92ae6402</AnalyticsClientId>
  <AllowAnalytics>False</AllowAnalytics>
</Settings>
```

And this will disable analytics and avoid the prompt.  It doesn't matter what GUID you provide for AnalyticsClientId.  You could use this one or invent another one, it doesn't matter because there won't be any analytics collected unless the user changes the setting in the options dialog.
![image](https://user-images.githubusercontent.com/18707114/108260410-2a222780-7117-11eb-971c-e9953552d86f.png)

**Comment by rcadmin19** [comment]
Thanks Chris! Actually this was the method I finally used because I couldn't find another way :)

**Comment by lovettchris** [comment]
Ok, thanks for closing the issue.  I added this info to the help page at https://microsoft.github.io/XmlNotepad/help/analytics/
