### ISSUE TITLE
Sugg: Better output for "statistics"

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [microsoft/XmlNotepad#77]
The current output of statistics is missing
- the name of the analysed file
- a way to save the data to txt-file

Please consider to add it.

**Comment by lovettchris** [comment]
Fixed in version 2.8.0.27

you can save the output of xmlstats to a file using normal command line redirection like this:

xmlstats foo.xml > myfile.txt

**Comment by Pierre-de-la-Verre** [comment]
> Fixed in version 2.8.0.27

Thanks. 
Buuuuut - when I see that the suggestions are implemented so quickly ...: The header could be expanded with USER: ... and with  CURRENT DATE/TIME: .. and ..
Just as an idea, not important. Could be helpful for some people sometimes

 
> you can save the output of xmlstats to a file using normal command line redirection like this:
> 
> xmlstats foo.xml > myfile.txt

Yes, it is possible, but not as handy as the other functions are 
- the exe is placed in the %temp%/xmlnotepad
- when I have already the file and the command offered in the GUI, so the "save as .." is really missing
- this kind of output does not include the (yesterday added) new header

**Comment by lovettchris** [comment]
Well I'm "bundling" the "xmlstats" command line tool with Xml Notepad and the idea of showing you the command line like this rather than hiding is is that xmlstats can do more than the GUI can really do.  For example, you can run "xmlstats *.xml" to generate reports on entire directories of XML documents.  So I wanted the curious user to be able to discover this.  Building a GUI for all that is a lot of work, so I was also being lazy :-)  The UI or xml stats is really just me saying "hey there's this cool tool call xmlstats, check it out"...

**Comment by Pierre-de-la-Verre** [comment]
Thanks, OK for me.
