### ISSUE TITLE
64MB XML creates a 64MB HTML - extremely slow display

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [microsoft/XmlNotepad#91]
I have a XML with approx. 64 MB, with a XSLT I can create a 60MB HTML within a few seconds (with another software).  With current Firefox I can open and display and navigate inside the file (there is a lot of expand/collapse of sub-tables in the HTML) - also in some seconds.

But - with XMLNotepad and its user-friendly feature "create output and display it" - my RAM usage runs immediately up to 2.1 - 2.2 GB, it displays a few lines of output-file, and keeps running on full CPU-load. That's all ...

It seems that this heavy load invokes an overload, caused by the limit of 2.4 GB RAM usage (my PC has Win 10 64 and 16 GB RAM). So maybe you can create a kind of "overload-detector" which checks the RAM or the used time or do something else to avoid this behaviour.

**Comment by lovettchris** [comment]
Thanks for the bug report.  I'd be curious to know if the attached command line xslt tool has the same behavior or not.
[xsl.zip](https://github.com/microsoft/XmlNotepad/files/6496199/xsl.zip).

**Comment by Pierre-de-la-Verre** [comment]
How to use the EXE?

**Comment by lovettchris** [comment]
hopefully you are familiar with using a terminal window...
```
d:\Tools>xsl -?

Usage: xsl -s xsl_file -o output_dir <xml_filenames>
Transforms the given xml files using the given xsl file
Options:
  -s xsl_file        the XSLT transform to use
  -e                 print output to stdout instead of a file
  -o output_dir      the folder to put the transformed output
  xml_filenames      the XML files to transform (supports wildcards)

The default output directory is the same folder as the XML file, and the output files will have the same name as the XML files but have a different file extension
```

**Comment by Pierre-de-la-Verre** [comment]
Oh, it's "this exe"...

Yeah, it works fine and quick and also the display with Firefox is OK. For me, the "display function" in XmlNotepad is the problem.

I can not upload the data, but maybe you can create it by yourself:
- Download Treesize Professional from here: https://www.jam-software.com/treesize (30 days free)
- analyse your harddisk or your network drive
- save report as XML. This saves also the XSLT

Maybe you can reproduce the issue.

**Comment by lovettchris** [comment]
Oh, very interesting that the command line tool works fine as it is using the same .NET XSLT engine under the covers.  Thanks for the repro.  I installed your app (looks very handy by the way) and I exported a report (before scan was finished) and I only got one file: "jam_13928300824859495629157.xml".  Perhaps I have to wait for scan to finish to get the xslt?  I used this menu:

![image](https://user-images.githubusercontent.com/18707114/118548163-d4a5e880-b70e-11eb-8b12-2a77f877bc29.png)

**Comment by Pierre-de-la-Verre** [comment]
Yes, the used command is OK.
Maybe we have a problem with the software-version? Mine is 6, yours is the current (8 or 9?). But nevertheless here is the XSLT - I hope it works with your data too.

[tsizepro.zip](https://github.com/microsoft/XmlNotepad/files/6499441/tsizepro.zip)

**Comment by lovettchris** [comment]
Interesting, so I did some profiling and it seems all the time is in the web browser and not in the XSLT transform itself, this is what I see on one of my TreeSize XML files.
```
Transform in 63 milliseconds
Browser loaded in 3180 milliseconds
```
It seems that the WinForms web browser component is much slower than Edge or Chrome web browsers.  Because the XSLT output file loads in Edge in much less than 1 second.  The fix to this then would be to find an embeddable Chrome control...

I also found a memory usage bug in XML notepad to do with extremely large XML documents.  TreeSize on my C drive outputs a 540 megabyte XML file.  This one hits a memory exceeded exception while loading.  The memory exception is related to the way XML notepad is keeping track of line number information for each node in the document so it can do error reporting.  So large documents might be eating up a lot of available RAM which will also make the XSLT browsing even slower.  So I may add a check for XML file size and turn off that feature when the file exceeds a certain size...

**Comment by TauerOne** [comment]
CefSharp is an embeddable Chrome control.  https://cefsharp.github.io/

**Comment by lovettchris** [comment]
Good find, thanks.  Looks promising.  One thing their sample app requires however is for the compile to choose x86 or x64 build.  I want XmlNotepad to remain "AnyCPU" for portability, so I'll need to figure out how to deal with that, so it's not a simple rip and replace unfortunately...

**Comment by lovettchris** [comment]
Even better option: https://developer.microsoft.com/en-us/microsoft-edge/webview2/#download-section
I added support for WebView to in version 2.8.0.35, let me know if it solves the perf problem, thanks.

**Comment by Pierre-de-la-Verre** [comment]
I tried 2.8.0.35 and compared to .34
- 3 MB XML creates 3 MB HTML: 0.5 sec to calculate, 28 sec to display for both versions
- 60 MB XML creates 62 MB HTML: 1-2 sec. to calculate; display skipped after minutes with full CPU and slow rising the RAM to 1.6 GB

**Comment by lovettchris** [comment]
rats, so you are saying there's no difference.  Did you actually install the WebView 2 runtime though?  I changed XML Notepad to use WebView2 if it is there, otherwise it falls back on the old web browser control...  if your .35 version is using WebView2 then you should see a new WebView2Cache folder in %LOCALAPPDATA%\Microsoft\Xml Notepad.

**Comment by Pierre-de-la-Verre** [comment]
I thought it is included in MSI ... I will check and report later.
________________________________

**Comment by lovettchris** [comment]
Sweet!  Thanks for testing it out and for pushing me to fix it :-) i can try and bundle the WebView2 installer, but it makes the installer a lot more complicated...  plus I'm worried how the "update" cycle would happen if I do that... I want WebView2 to be able to update itself with any bug fixes down the road...

**Comment by lovettchris** [comment]
Closing as this is resolved now using the new WebView2 feature.
