### ISSUE TITLE
ctrl+A triggers "Save As" instead of ctrl+S

### ISSUE THREAD

**Issue by bsamesh** [microsoft/XmlNotepad#95]
Currently, ctrl+A triggers the "Save As" function and ctrl+S does nothing (not that I could notice anything is done).
Is it intentional?
I tried to select the whole text while editing a node using ctrl+A and suddenly the "Save As"  window showed up, not very intuitive.

Thanks,
Barak.

**Comment by lovettchris** [comment]
Hi, thanks for the bug report on Save As, I can see the same problem.  As for Ctrl+S, this works.  If you modify the file by editing something an asterix appears in the window title, then when you hit Ctrl+S that asterix disappears because the file is saved and is now up to date.  If you use another text editor on the file (like vs code) you will see the saved contents appears in the other editor.

**Comment by lovettchris** [comment]
The fix is included in 2.8.0.33 and the fix is to just remove the Ctrl+A shortcut from SaveAs which is what most apps have done also.
